### ISSUE TITLE
Sentry ability to turn off by configuration

### ISSUE THREAD

**Issue by jkuchar** [contributte/logging#13]
There are more environments:

- localhost - do not want to push to sentry
- CI - do not want to log to sentry
- staging - want to log to staging sentry
- production - want to log to production sentry

To be able to do CI and localhost I need some way how to turn disable sentry extension. Now it throws exception when I provide NULL in DSN.

(I use just parameters sections in confi.local.neon)

**Comment by f3l1x** [comment]
Hi. What about this #11?

**Comment by jkuchar** [comment]
Cool, that is exactely what I have come out with - I have copied extensions and implemented the same thing. When this PR will be in stable release? (tagged)

**Comment by f3l1x** [comment]
Tagged as v0.2.2.

**Comment by f3l1x** [comment]
I'm closing it, feel free to open another issue.
