### ISSUE TITLE
New version with Nette 3 support

### ISSUE THREAD

**Issue by RiKap** [contributte/logging#30]
Hi,
please can you release new version with Nette 3 support?

- I cannot use `^0.5.0` as it conflict with your requirements or minimum-stability.
- There is not `^0.4.0` even it is mentioned in readme. (It looks like that readme wes updated, without new release)
- And `dev-master` is not working as it install `v0.2.1` (Don't know why)

@f3l1x

**Comment by f3l1x** [comment]
Hi @RiKap.

I've just released v0.4.0. Can you please test it?

**Comment by RiKap** [comment]
Thank you. Yes i can.

**Comment by RiKap** [comment]
Hmm, it is not possible to use it wiht Tracy 2.7 as it is not allowed version in composer.

**Comment by f3l1x** [comment]
Bumped v0.4.1 (https://github.com/contributte/logging/releases/tag/v0.4.1)
