### ISSUE TITLE
Support for PHP 7.4

### ISSUE THREAD

**Issue by medhi** [contributte/logging#34]
It looks like `"sentry/sentry": "^1.0" ` is not compatible with PHP 7.4. Sentry has been upgraded to `sentry/sdk` package, which does not use Raven, so it doesn't work with Logging Sentry connector. I wasn't able to find any version combination to run this on PHP 7.4 :(

Can you help?

**Comment by josefsabl** [comment]
Rough implementation in my [PR](https://github.com/contributte/logging/pull/35). Not tested too much :-)
