### ISSUE TITLE
Is support php 8 planned?

### ISSUE THREAD

**Issue by real-antonin** [contributte/logging#40]

**Comment by f3l1x** [comment]
Hi @real-antonin, yep, PHP 8 is on the roadmap. Cannot tell you any ETA.

https://github.com/contributte/contributte/issues/31

**Comment by dada-amater** [comment]
Hi @f3l1x , I can see there is php8 in `dev-master`, but no release was made. Do you know when you plan the next release?

**Comment by f3l1x** [comment]
Bumped https://github.com/contributte/logging/releases/tag/v0.6.0

Thanks for pinging me.
