### ISSUE TITLE
tracy/tracy 2.8.x support

### ISSUE THREAD

**Issue by dada-amater** [contributte/logging#46]
Hi @f3l1x ,

this package requires `tracy/tracy` `~2.5.5|~2.6.2|~2.7.0`. But there is already `v2.8.3`. This is not important, but if there is no problem, it would be nice to update it. Thank you so much.

**Comment by f3l1x** [comment]
Yup, you're right. I am thinking about require 2.8.3 and above, like `^2.8.3`? What do you think?

**Comment by hermajan** [comment]
Or maybe if there is no other big changes it could be `>=2.5 <2.9` in version 0.6.1?

**Comment by dada-amater** [comment]
> Yup, you're right. I am thinking about require 2.8.3 and above, like `^2.8.3`? What do you think?

I agree with @hermajan. It is not a good habit to require only the latest version. If there are two @f3l1x, one requires on his project `~2.5.5|~2.6.2|~2.7.0` and the second requires `^2.8.3` on another project, it would be quite hard to match both conditions ;-).

**Comment by f3l1x** [comment]
Ok guys, I will add 2.8 to composer and release 0.6.1.

**Comment by f3l1x** [comment]
https://github.com/contributte/logging/releases/tag/v0.6.1
