### ISSUE TITLE
Slack - problem with multiple formatters

### ISSUE THREAD

**Issue by f3l1x** [contributte/logging#7]
```
Nette\DI\ServiceCreationException

Multiple services of type Contributte\Logging\Slack\Formatter\IFormatter found: slack.formatter.1, slack.formatter.2, slack.formatter.3, slack.formatter.4, slack.formatter.5
```

**Comment by josefzajac** [comment]
Hi @f3l1x , any progress here? Or idea I can try to work on?

**Comment by f3l1x** [comment]
@josefzajac Fixed. Could you please try `contributte/logging: dev-master`?

**Comment by josefzajac** [comment]
Works, Thx a lot
<img width="556" alt="contributte slack" src="https://user-images.githubusercontent.com/8426378/31722508-8f9bf64c-b41c-11e7-8d7c-72c938cb6f22.png">

**Comment by f3l1x** [comment]
Cool, have fun. ;-) Feel free to send PR or open an issue.
