### ISSUE TITLE
\Throwable

### ISSUE THREAD

**Issue by kralmichal** [contributte/logging#8]
Hi.

\Throwable interface is not available in PHP 5.6, it was introduced in PHP7. Exceptions are tested against https://github.com/contributte/logging/blob/master/src/Sentry/SentryLogger.php#L32 . No exceptions will make it through this condition.

**Comment by f3l1x** [comment]
You're right. Shame on me. 👍

**Comment by kralmichal** [comment]
I am happy to send PR. I just wanna know if removing all conditions regarding \Throwable is the correct solution.

**Comment by f3l1x** [comment]
It would be great, could you do that? :-)

**Comment by kralmichal** [comment]
Yeah. I'm going to send it tomorrow.

**Comment by f3l1x** [comment]
How is it going? Any updates?

**Comment by kralmichal** [comment]
Sorry, wasn't feeling well last week. It's on top of my todo list.

**Comment by f3l1x** [comment]
Resolved via #9
